<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
            [
                'title_ar' => 'title_ar',
                'title_en' => 'title_en',
                'file' => 'file',
                'price' => '10',
                'discount' => '10',
                'description_ar' => 'description_ar',
                'description_en' => 'description_en',
                'views' => '10',
                'lat' => '0.55',
                'lng' => '0.55',
                'show' => 'BEST-DEALS',
                'type' => 'NEW',
                'status' => 'ACTIVE',
                'category_id' => 1,
                'sub_category_id' => 8,
            ],
        ];

        foreach ($data as $key => $value) {
            Product::create([
                'title_ar' => $value['title_ar'],
                'title_en' => $value['title_en'],
                'file' => $value['file'],
                'status' => $value['status'],
                'price' => $value['price'],
                'discount' => $value['discount'],
                'description_ar' => $value['description_ar'],
                'description_en' => $value['description_en'],
                'views' => $value['views'],
                'lat' => $value['lat'],
                'lng' => $value['lng'],
                'show' => $value['show'],
                'type' => $value['type'],
                'category_id' => $value['category_id'],
                'sub_category_id' => $value['sub_category_id'],
            ]);
        }
    }
}
